// Time-lock seals every gift with drand (quicknet) so nobody can read it before its time,
// not even from the source code. Reads secrets/content.json (never committed), writes js/sealed.js.
// Usage: npm run seal
import { readFile, writeFile } from 'node:fs/promises';
import { timelockEncrypt, defaultChainInfo, Buffer } from 'tlock-js';
import { GIFTS, FINALE } from '../js/config.js';

// Chain parameters ship with tlock-js, so sealing needs no network.
const offlineClient = {
  options: { disableBeaconVerification: false, noCache: false },
  chain: () => ({ baseUrl: 'offline', info: async () => defaultChainInfo }),
};

/** First beacon round published at or after `ms`, so nothing opens even a second early. */
export function roundFor(ms, info = defaultChainInfo) {
  const sinceGenesis = ms / 1000 - info.genesis_time;
  return Math.max(1, Math.ceil(sinceGenesis / info.period) + 1);
}

export async function seal(ms, payload) {
  return timelockEncrypt(roundFor(ms), Buffer.from(JSON.stringify(payload)), offlineClient);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const content = JSON.parse(await readFile(new URL('../secrets/content.json', import.meta.url), 'utf8'));
  const out = {};
  for (const g of GIFTS) {
    if (!content.gifts[g.id]) throw new Error(`secrets/content.json has no content for gift "${g.id}"`);
    out[g.id] = await seal(g.unlockAt, content.gifts[g.id]);
  }
  out.finale = await seal(FINALE.unlockAt, content.finale);
  const body = Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n');
  await writeFile(new URL('../js/sealed.js', import.meta.url),
    `// Generated by scripts/seal.mjs. Time-lock encrypted with drand; do not edit.\nexport const SEALED = {\n${body}\n};\n`);
  console.log(`sealed ${Object.keys(out).length} items -> js/sealed.js`);
}
